erDiagram
    %% Relationships
    USERS ||--o{ LIBRARIES : "has"
    LIBRARIES ||--o{ BOOKS : "contains"
    CONTRIBUTORS ||--o{ BOOK_CONTRIBUTOR_MAP : "contributes_to"
    BOOKS ||--o{ CHAPTERS : "has"
    CANNON ||--o{ SERIES : "organises"
    SERIES ||--o{ BOOKS : "groups"
    BOOKS ||--o{ BOOK_CONTRIBUTOR_MAP : "has"
    BOOKS ||--o{ BOOK_FILES_MAP : "has"
    FILES ||--o{ BOOK_FILES_MAP : "associated_with"
    SERIES ||--o{ SERIES_FILES_MAP : "has"
    FILES ||--o{ SERIES_FILES_MAP : "associated_with"
    CANNON ||--o{ CANNON_FILES_MAP : "has"
    FILES ||--o{ CANNON_FILES_MAP : "associated_with"
    CONTRIBUTORS ||--o{ CONTRIBUTOR_FILES_MAP : "has"
    FILES ||--o{ CONTRIBUTOR_FILES_MAP : "associated_with"
    BOOKS ||--o{ BOOK_GENRE_MAP : "assigned_to"
    GENRES ||--o{ BOOK_GENRE_MAP : "contains"
    BOOKS ||--o{ BOOK_TAG_MAP : "assigned_to"
    TAGS ||--o{ BOOK_TAG_MAP : "contains"
    CONTRIBUTORS ||--o{ CONTRIBUTOR_GENRE_MAP : "assigned_to"
    GENRES ||--o{ CONTRIBUTOR_GENRE_MAP : "contains"
    CONTRIBUTORS ||--o{ CONTRIBUTOR_TAG_MAP : "assigned_to"
    TAGS ||--o{ CONTRIBUTOR_TAG_MAP : "contains"
    USERS ||--o{ USER_SERVER_MAP : "mapped_to"
    SERVER ||--o{ USER_SERVER_MAP : "mapped_to"
    LIBRARIES ||--o{ LIBRARY_SERVER_MAP : "mapped_to"
    SERVER ||--o{ LIBRARY_SERVER_MAP : "mapped_to"

    %% Entities
    USERS {
        string user_id PK
        string name
        bool light_mode
        string prefered_server
        string file_id FK
    }
    SERVER {
        string server_id PK
        string plex_id
        string name
        string notes
    }
    LIBRARIES {
        string library_id PK
        string plex_id
        string name
        string type
        string path
        string file_id FK
    }
    CONTRIBUTORS {
        string contributor_id PK
        string plex_id
        string asin_id
        string asin_txt
        string name
        string type
        string description
    }
    CANNON {
        string cannon_id PK
        string title
        string description
    }
    SERIES {
        string series_id PK
        string cannon_id FK
        string title
        string description
    }
    BOOKS {
        string book_id PK
        string series_id FK
        string cannon_id FK
        string plex_id
        string asin_id
        string asin_txt
        string isbn_id
        string library_id FK
        string title
        string duration
        string description
        bool in_library
        bool has_started
        bool has_finished
        int publish_year
    }
    CHAPTERS {
        int chapter_id PK
        string book_id FK
        string plex_id
        string title
        string chapter_index_txt
        int chapter_index_number
        int start_time_offset
        int end_time_offset
        int duration
        bool has_started
        bool has_finished
    }
    GENRES {
        int genre_id PK
        string genre_name
        string source_taxonomy
        string source_id
        string source_txt
    }
    TAGS {
        int tag_id PK
        string tag_name
        string source_taxonomy
        string source_id
        string source_txt
    }
    FILES {
        string file_id PK
        string file_path
        int file_size_bytes
        string container
        string notes
    }
    BOOK_FILES_MAP {
        int id PK
        string book_id FK
        string file_id FK
        string description
    }
    USER_SERVER_MAP {
        int id PK
        string user_id FK
        string server_id FK
        string description
    }
    LIBRARY_SERVER_MAP {
        int id PK
        string library_id FK
        string server_id FK
        string description
    }
    SERIES_FILES_MAP {
        int id PK
        string series_id FK
        string file_id FK
        string description
    }
    CANNON_FILES_MAP {
        int id PK
        string cannon_id FK
        string file_id FK
        string description
    }
    CONTRIBUTOR_FILES_MAP {
        int id PK
        string contributor_id FK
        string file_id FK
        string description
    }
    BOOK_CONTRIBUTOR_MAP {
        int id PK
        string book_id FK
        string contributor_id FK
        string contributor_type
    }
    BOOK_GENRE_MAP {
        int id PK
        string book_id FK
        int genre_id FK
    }
    BOOK_TAG_MAP {
        int id PK
        string book_id FK
        int tag_id FK
    }
    CONTRIBUTOR_GENRE_MAP {
        int id PK
        string contributor_id FK
        int genre_id FK
    }
    CONTRIBUTOR_TAG_MAP {
        int id PK
        string contributor_id FK
        int tag_id FK
    }